codes <- tibble::tribble(
  ~code, ~name,
  "ABT773",	"Abbott 773",
  "AESCUL",	"Aesculin",
  "AGMATI",	"Agmatine",
  "AMDPEN",	"Amidinopenicillin subclass",
  "AMICYC",	"Aminocyclitol class",
  "AMIFLO",	"Amifloxacin",
  "AMIGLY",	"Aminoglycoside class",
  "AMIKAC",	"Amikacin",
  "AMIPEN",	"Aminopenicillin subclass",
  "AMOCL2",	"Amoxicillin/ Clav.Acid */2",
  "AMOCL4",	"Amoxicillin/ Clav. Acid 4:1",
  "AMOCLA",	"Amoxicillin/ Clavulanic Acid",
  "AMOXIC",	"Amoxicillin",
  "AMP100",	"Ampicillin 100 ug/ml",
  "AMP200",	"Ampicillin 200 ug/ml",
  "AMPHOT",	"Amphotericin B",
  "AMPICI",	"Ampicillin",
  "AMPSUL",	"Ampicillin/ Sulbactam",
  "ANIDUL",	"Anidulafungin",
  "ANSAMY",	"Rifabutin",
  "ANSMYC",	"Ansamycin class",
  "APALCI",	"Apalcillin",
  "APOXIC",	"Apoxicillin",
  "APRAMY",	"Apramycin",
  "ARABIN",	"Arabinose",
  "ARABIT",	"Arabitol",
  "ARBEKA",	"Arbekacin",
  "ARGINI",	"Arginine",
  "ASPOXI",	"Aspoxicillin",
  "ASTROM",	"Astromycin",
  "AVILAM",	"Avilamycin",
  "AZD256",	"AZD2563",
  "AZITHR",	"Azithromycin",
  "AZLOCI",	"Azlocillin",
  "AZT1",	"Aztreonam 1 ug/ml",
  "AZTREO",	"Aztreonam",
  "BACAMP",	"Bacampicillin",
  "BACITR",	"Bacitracin",
  "BAMMYC",	"Bambermycin class",
  "BAY12",	"BAY12-8039",
  "BERBER",	"Berberine",
  "BESIFL",	"Besifloxacin",
  "BETA",	"Beta-lactamase",
  "B",	"HAEM Beta-haemolysis",
  "BIAPEN",	"Biapenem (L-627)",
  "BLACT",	"Beta-lactam class",
  "BLINHB",	"Beta-lactam Inhibitor class",
  "B",	"MGLU B-Methyl Glucoside",
  "CAPREO",	"Capreomycin",
  "CAPRYL",	"Caprylic Acid",
  "CARBAD",	"Carbadox",
  "CARBAP",	"Carbapenem class",
  "CARBEN",	"Carbenicillin",
  "CARPEN",	"Carboxypenicillin subclass",
  "CASPOF",	"Caspofungin",
  "CATALA",	"Catalase",
  "CCARB",	"Carbacephem subclass",
  "CEFACL",	"Cefaclor",
  "CEFADR",	"Cefadroxil",
  "CEFAMA",	"Cefamandole",
  "CEFATR",	"Cefatrizine",
  "CEFAXE",	"Cefuroxime (axetil)",
  "CEFAZE",	"Cefazedon",
  "CEFAZO",	"Cefazolin",
  "CEFBUP",	"Cefbuperazone",
  "CEFCAP",	"Cefcapene",
  "CEFCLA",	"Cefepime/ Clavulanic Acid",
  "CEFCLI",	"Cefclidin",
  "CEFDIN",	"Cefdinir",
  "CEFDIT",	"Cefditoren",
  "CEFEP4",	"Cefepime 4 ug/ml",
  "CEFEPI",	"Cefepime",
  "CEFETA",	"Cefetamet",
  "CEFIXI",	"Cefixime",
  "CEFMEN",	"Cefmenoxime",
  "CEFMET",	"Cefmetazole",
  "CEFMIN",	"Cefminox",
  "CEFMTM",	"Cefmetamet",
  "CEFO32",	"Cefotaxime 32 ug/ml",
  "CEFONI",	"Cefonicid",
  "CEFOPE",	"Cefoperazone",
  "CEFORA",	"Ceforanide",
  "CEFOSE",	"Cefoselis",
  "CEFOTA",	"Cefotaxime",
  "CEFOTE",	"Cefotetan",
  "CEFOTI",	"Cefotiam",
  "CEFOVE",	"Cefovecin",
  "CEFOXI",	"Cefoxitin",
  "CEFOZO",	"Cefozopran",
  "CEFPAM",	"Cefpiramide",
  "CEFPIM",	"Cefpimizole",
  "CEFPOD",	"Cefpodoxime",
  "CEFPOM",	"Cefpirome",
  "CEFPRO",	"Cefprozil",
  "CEFQUI",	"Cefquinome",
  "CEFROX",	"Cefroxidime",
  "CEFSUL",	"Cefsulodin",
  "CEFTAR",	"Ceftaroline",
  "CEFTAZ",	"Ceftazidime",
  "CEFTER",	"Cefteram",
  "CEFTEZ",	"Ceftezole",
  "CEFTIB",	"Ceftibuten",
  "CEFTIF",	"Ceftiofur",
  "CEFTIX",	"Ceftioxadine",
  "CEFTIZ",	"Ceftizoxime",
  "CEFTOB",	"Ceftobiprole",
  "CEFTRI",	"Ceftriaxone",
  "CEFURO",	"Cefuroxime (sodium)",
  "CEFUZO",	"Cefuzonam",
  "CELLOB",	"Cellobiose",
  "CEPALE",	"Cefalexin",
  "CEPHAC",	"Cephacetril",
  "CEPHAL",	"Cephalothin",
  "CEPHAP",	"Cephapirin",
  "CEPHEM",	"Cephem class",
  "CEPHOR",	"Cephem (oral) class",
  "CEPHPA",	"Cephem (parenteral) class",
  "CEPHRA",	"Cephradine",
  "CEPLOR",	"Cephaloridine",
  "CHLORA",	"Chloramphenicol",
  "CHLTET",	"Chlortetracycline",
  "CI983",	"CI-983",
  "CINOXA",	"Cinoxacin",
  "CIPROF",	"Ciprofloxacin",
  "CIPROP",	"CIPROP",
  "CITRAT",	"Citrate",
  "CLARYT",	"Clarithromycin",
  "CLIN32",	"Clindamycin 32 ug/ml",
  "CLINAF",	"Clinafloxacin",
  "CLINDA",	"Clindamycin",
  "CLISPE",	"Clindamycin/ Spectinomycin",
  "CLOFAM",	"Clofazimine",
  "CLOXAC",	"Cloxacillin",
  "CMYC",	"Cephamycin subclass",
  "COAGUL",	"Coagulase",
  "COLFAZ",	"Colfazamine",
  "COLIST",	"Colistin",
  "COLMET",	"Colistimethate",
  "COMBO",	"Combination class",
  "CORAL",	"Cephem (oral) class",
  "COUMER",	"Coumermycin",
  "COXA",	"Oxacephem subclass",
  "CPAREN",	"Cephem (parenteral) class",
  "CPCA",	"Cond. Pyridone Carboxylic Acid class",
  "CSPOR",	"Cephalosporin class",
  "CSPOR1",	"Cephalosporin I-Generation subclass",
  "CSPOR2",	"Cephalosporin II-Generation subclass",
  "CSPOR3",	"Cephalosporin III-Generation subclass",
  "CSPOR4",	"Cephalosporin IV-Generation subclass",
  "CSPOR5",	"Cephalosporin V-Generation subclass",
  "CYCLAC",	"Cyclacillin",
  "CYCLOS",	"Cycloserine",
  "DALBAV",	"Dalbavancin",
  "DALFOP",	"Dalfopristin",
  "DANOFL",	"Danofloxacin",
  "DAPT25",	"Daptomycin 25mg/L Ca",
  "DAPT50",	"Daptomycin 50mg/L Ca",
  "DAPTOM",	"Daptomycin",
  "DEMECY",	"Demeclocycline",
  "DIBEKA",	"Dibekacin",
  "DICLOX",	"Dicloxacillin",
  "DIFLOX",	"Difloxacin",
  "DIRITH",	"Dirithromycin",
  "DORIPE",	"Doripenem",
  "DOXYCY",	"Doxycycline",
  "DTEST1",	"DTest1",
  "DTEST2",	"DTest2",
  "ENOXA",	"Enoxacin",
  "ENROFL",	"Enrofloxacin",
  "ERTAPE",	"Ertapenem",
  "ERY32",	"Erythromycin 32 ug/ml",
  "ERYSCH",	"Erythromycin/ Sulphachloropyrid",
  "ERYSDI",	"Erythromycin/ Sulphadimethoxine",
  "ERYSPE",	"Erythromycin/ Spectinomycin",
  "ERYSUL",	"Erythromycin/ Sulfizoxazole",
  "ERYTH",	"Erythromycin",
  "ESBL",	"Extended spectrum beta-lactamase",
  "ETHAMB",	"Ethambutol",
  "ETHION",	"Ethionamide",
  "FAROPE",	"Faropenem",
  "FLAVOM",	"Flavomycin",
  "FLEROX",	"Fleroxacin",
  "FLOMOX",	"Flomoxef",
  "FLORFE",	"Florfenicol",
  "FLQUIN",	"Fluoroquinolone class",
  "FLUCLO",	"Flucloxacillin",
  "FLUCON",	"Fluconazole",
  "FLUCYT",	"5-Flucytosine",
  "FLUMEQ",	"Flumequine",
  "FOPSUL",	"Cefoperazone/ Sulbactam",
  "FOSFOM",	"Fosfomycin",
  "FOSG6P",	"Fosfomycin + Glucose6Phosphate",
  "FOSMYC",	"Fosfomycin class",
  "FOSTRO",	"Fosfomycin-trometamol",
  "FOT1",	"Cefotaxime 1 ug/ml",
  "FOXSCR",	"Cefoxitin Screen Test",
  "FPINHB",	"Folate Pathway Inhibitor class",
  "FR1",	"FR1",
  "FR10",	"FR10",
  "FR12",	"FR12",
  "FR13",	"FR13",
  "FR14",	"FR14",
  "FR15",	"FR15",
  "FR16",	"FR16",
  "FR17",	"FR17",
  "FR18",	"FR18",
  "FR19",	"FR19",
  "FR20",	"FR20",
  "FR21",	"FR21",
  "FR22",	"FR22",
  "FR23",	"FR23",
  "FR24",	"FR24",
  "FR25",	"FR25",
  "FR26",	"FR26",
  "FR27",	"FR27",
  "FR28",	"FR28",
  "FR29",	"FR29",
  "FR3",	"FR3",
  "FR30",	"FR30",
  "FR31",	"FR31",
  "FR32",	"FR32",
  "FR5",	"FR5",
  "FR6",	"FR6",
  "FR7",	"FR7",
  "FR8",	"FR8",
  "FR9",	"FR9",
  "FRAMYC",	"Framycetin",
  "FRUCTO",	"Fructose",
  "FURALT",	"Furaltadone",
  "FURAZO",	"Furazolidone",
  "FUSACI",	"Fusidic Acid",
  "FUSIDA",	"Fusidate",
  "GARENO",	"Garenoxacin",
  "GARLIC",	"Garlic",
  "GATIFL",	"Gatifloxacin",
  "GE1000",	"Gentamicin 1000 ug/ml",
  "GE2000",	"Gentamicin 2000 ug/ml",
  "GEMIFL",	"Gemifloxacin",
  "GEN128",	"Gentamicin 128 ug/ml",
  "GEN500",	"Gentamicin 500 ug/ml",
  "GENTA1",	"Gentamicin 1024 ug/ml",
  "GENTAM",	"Gentamicin",
  "GLUCOS",	"Glucose",
  "GLYCER",	"Glycerol",
  "GLYCO",	"Glycopeptide class",
  "GREPAF",	"Grepafloxacin",
  "HETACI",	"Hetacillin",
  "HIPPUR",	"Hippurate hydrolysis",
  "HODGE",	"Hodge Test",
  "IB367",	"IB-367",
  "IBAFLO",	"Ibafloxacin",
  "ICLAPR",	"Iclaprim",
  "IMIDAZ",	"Imidazole class",
  "IMIP32",	"Imipenem 32 ug/ml",
  "IMIPEN",	"Imipenem",
  "INDOLE",	"Indole",
  "INOSIT",	"Inositol",
  "ISEPAM",	"Isepamycin",
  "ISONIA",	"Isoniazid",
  "ISOPEN",	"Isoxazolyl Penicillin subclass",
  "ITRACO",	"Itraconazole",
  "JOSAMY",	"Josamycin",
  "KANAMY",	"Kanamycin",
  "KETOCO",	"Ketoconazole",
  "KETOLI",	"Ketolide class",
  "LEVOFL",	"Levofloxacin",
  "LINCOM",	"Lincomycin",
  "LINCOS",	"Lincosamide class",
  "LINEZO",	"Linezolid",
  "LINFLO",	"Linopristin-Flopristin",
  "LINNEO",	"Lincomycin/ Neomycin 2:1 ratio",
  "LINSPE",	"Lincomycin/ Spectinomycin",
  "LIPGLY",	"Lipoglycopeptide subclass",
  "LIPOPE",	"Lipopeptide class",
  "LOMEFL",	"Lomefloxacin",
  "LORACA",	"Loracarbef",
  "LYSINE",	"Lysine",
  "MACCON",	"Growth on MacConkey",
  "MACRO",	"Macrolide class",
  "MALONA",	"Malonate",
  "MALTOS",	"Maltose",
  "MANNIT",	"Mannitol",
  "MARBOF",	"Marbofloxacin",
  "MECILL",	"Mecillinam",
  "MEROPE",	"Meropenem",
  "METHCY",	"Methacycline",
  "METHIC",	"Methicillin",
  "METRON",	"Metronidazole",
  "MEZLO",	"Mezlocillin",
  "MEZSUL",	"Mezlocillin/ Sulbactam",
  "MICAFU",	"Micafungin",
  "MICRON",	"Micronomycin",
  "MIDEKA",	"Midekamycin",
  "MINOCY",	"Minocycline",
  "MONOBA",	"Monobactam class",
  "MOTILI",	"Motility",
  "MOXALA",	"Moxalactam",
  "MOXIFL",	"Moxifloxacin",
  "MUPIRO",	"Mupirocin",
  "NAFCIL",	"Nafcillin",
  "NALAC",	"Nalidixic Acid",
  "NARASI",	"Narasin",
  "NEGCTL",	"Negative Growth Control",
  "NEOMYC",	"Neomycin",
  "NETILM",	"Netilmicin",
  "NFURAN",	"Nitrofuran class",
  "NIMIDA",	"Nitroimidazole class",
  "NIT16",	"Nitrofurantoin 16ul",
  "NITFUR",	"Nitrofurazone",
  "NITRAT",	"Nitrate",
  "NITRO",	"Nitrofurantoin",
  "NITSUL",	"Nitrofurantoin/ Sulphadrazine",
  "NORFLO",	"Norfloxacin",
  "NOVOBI",	"Novobiocin",
  "NYSTAN",	"Nystantin",
  "OFLOXA",	"Ofloxacin",
  "OLAQUI",	"Olaquindox",
  "OLEAND",	"Oleandomycin",
  "OPTOCH",	"Optochin Sensitivity",
  "ORBIFL",	"Orbifloxacin",
  "ORITAV",	"Oritavancin",
  "ORMSUL",	"Ormetoprim/ Sulphadimethoxine",
  "ORNIST",	"Ornithine Spot Test",
  "ORNITH",	"Ornithine",
  "OXACIL",	"Oxacillin + 2% NaCl",
  "OXAZOL",	"Oxazolidinone class",
  "OXIDAS",	"Oxidase",
  "OXOACI",	"Oxolinic Acid",
  "OXTSCH",	"Oxytet/Tylosin Tar/Sulphachlor",
  "OXTSDI",	"Oxytet/Tylosin Tar/Sulphadimet",
  "OXYCEP",	"Oxyimino Cephalosporin subclass",
  "OXYSCH",	"Oxytetracycline/ Sulphachloropy",
  "OXYTET",	"Oxytetracycline",
  "PASRAA",	"Para-aminosalicylic acid",
  "PEN003",	"Penicillin 0.03ug",
  "PENCIL",	"Penicillin class",
  "PENIC8",	"Penicillin 8 ug/ml",
  "PENICA",	"Penicillin 1-2-8 ug/ml",
  "PENICI",	"Penicillin",
  "PENMEN",	"Penicillin(meningitis)",
  "PENNME",	"Penicillin(nonmeningitis)",
  "PENNOV",	"Penicillin/ Novobiocin",
  "PENORA",	"Penicillin (Oral)",
  "PENSCH",	"Penicillin/ Sulphachloropyridaz",
  "PENSTR",	"Penicillin/ Streptomycin",
  "PERFLO",	"Perfloxacin",
  "PHENIC",	"Phenicol class",
  "PHEPEN",	"Phenoxymethylpenicillin",
  "PIGMEN",	"Pigment",
  "PIPACI",	"Pipemidic Acid",
  "PIPERA",	"Piperacillin",
  "PIPTAZ",	"Piperacillin/ Tazobactam",
  "PIRLIM",	"Pirlimycin",
  "PIVMEC",	"Pivmecillinam",
  "PLUERO",	"Plueromutilin class",
  "POD4",	"Cefpodoxime 4 ug/ml",
  "PODCLA",	"Cefpodoxime/ Clavulanic Acid",
  "POLION",	"Polyether Ionophore class",
  "POLPEP",	"Polypeptide class",
  "POLYB",	"Polymyxin B",
  "POSACO",	"Posaconazole",
  "POSCTL",	"Positive Growth Control",
  "PREMAF",	"Premafloxacin",
  "PRISTI",	"Pristinamycin",
  "PSPEN",	"Penicillinase-stable Penicillin class",
  "PYRUVA",	"Pyruvate",
  "QUIN",	"Quinolone class",
  "QUINOL",	"Quinolones",
  "QUINS1",	"Quinolones subclass 1",
  "QUINUP",	"Quinupristin",
  "R28965",	"RU 28965",
  "RAFFIN",	"Raffinose",
  "RAMOPL",	"Ramoplanin",
  "RAVUCO",	"Ravuconazole",
  "RAZUPE",	"Razupenem",
  "RHAMNO",	"Rhamnose",
  "RIFAMP",	"Rifampin",
  "RIFMYC",	"Rifamycin class",
  "ROKITA",	"Rokitamycin",
  "ROXITH",	"Roxithromycin",
  "S21420",	"Schering 21420",
  "S21561",	"Schering 21561",
  "S21562",	"Schering 21562",
  "S22591",	"Schering 22591",
  "S29482",	"Schering 29482",
  "S29486",	"Schering 29486",
  "S34343",	"Schering 34343",
  "S38609",	"Schering 38609",
  "SALCTL",	"Positive Control +2% NaCl",
  "SALINO",	"Salinomycin",
  "SANFET",	"Sanfetrinem",
  "SARAFL",	"Sarafloxacin",
  "SB2LB2",	"SB265805/ LB20304",
  "SBQLO",	"SB265805",
  "SDIMET",	"Sulphadimethoxine",
  "SIPRAM",	"Sipramycin",
  "SISOMY",	"Sisomycin",
  "SITAFL",	"Sitafloxacin",
  "SORBIT",	"Sorbitol",
  "SPARFL",	"Sparfloxacin",
  "SPECT",	"Spectinomycin",
  "SPIRAM",	"Spiramycin",
  "ST1000",	"Streptomycin 1000 ug/ml",
  "ST2000",	"Streptomycin 2000 ug/ml",
  "STREPT",	"Streptomycin",
  "STRGRA",	"Streptogramin class",
  "SUCROS",	"Sucrose",
  "SULAMI",	"Sulfonamide subclass",
  "SULBAC",	"Sulbactam",
  "SULBEN",	"Sulbenicillin",
  "SULCHL",	"Sulphachloropyridazine",
  "SULDIA",	"Sulphadiazine",
  "SULDIM",	"Sulphadimidine",
  "SULFAM",	"Sulphamethoxazole",
  "SULFIZ",	"Sulfisoxazole",
  "SULMET",	"Sulphamethazine",
  "SULOPE",	"Sulopenem",
  "SULTHI",	"Sulphathiazole",
  "SULTOS",	"Sultamicillin Tosilate",
  "SYNERC",	"Quinupristin/dalfopristin",
  "TANNAL",	"Tannalbit",
  "TAXCLA",	"Cefotaxime/clavulanic acid",
  "TAXMEN",	"Cefotaxime (meningitis)",
  "TAXNME",	"Cefotaxime (nonmeningitis)",
  "TAZCLA",	"Ceftazidime/clavulanic acid",
  "TAZOBA",	"Tazobactam",
  "TDA",	"TDA",
  "TEICOP",	"Teicoplanin",
  "TELAVA",	"Telavancin",
  "TELITH",	"Telithromycin",
  "TEMAFL",	"Temafloxacin",
  "TEMOCI",	"Temocillin",
  "TETCYC",	"Tetracycline class",
  "TETRA",	"Tetracycline",
  "THIAPH",	"Thiaphenicol",
  "TIAMUL",	"Tiamulin",
  "TICARC",	"Ticarcillin",
  "TICCLA",	"Ticarcillin/ Clavulanic Acid",
  "TIGECY",	"Tigecycline",
  "TILMIC",	"Tilmicosin",
  "TOBRAM",	"Tobramycin",
  "TOSUFL",	"Tosufloxacin",
  "TREHAL",	"Trehalose",
  "TRIBR",	"Trimethoprim/ Sulphadiazine",
  "TRICLA",	"Ceftriaxone/clavulanic acid",
  "TRIM",	"Trimethoprim",
  "TRIMEN",	"Ceftriaxone (meningitis)",
  "TRINME",	"Ceftriaxone (nonmeningitis)",
  "TRISUL",	"Trimethoprim/ Sulphamethoxazole",
  "TROSPE",	"Trospectinomycin",
  "TROVAF",	"Trovafloxacin",
  "TULATH",	"Tulathromycin",
  "TYLO",	"Tylosin (Tartrate/ Base)",
  "UNDECA",	"Undecanoic Acid",
  "UREA",	"Urea",
  "UREPEN",	"Ureidopenicillin subclass",
  "UVAURS",	"Uva Ursa",
  "VANCOM",	"Vancomycin",
  "VIRGIN",	"Virginiamycin",
  "VORICO",	"Voriconazole",
  "W49373",	"Win 49373-3",
  "W49548",	"Win 49548-2A",
  "W51692",	"Win 51692",
  "XYLOSE",	"Xylose",
  "YELPIG",	"Yellow Pigment"
)

codes$name <- gsub("Apoxi", "Aspoxi", codes$name)

codes$name_gen <- generalise_antibiotic_name(codes$name)

codes$ab_name <- ab_name(codes$name_gen)


codes$lev <- unlist(Map(f = function(a, b) {
  as.double(utils::adist(a, b,
                         ignore.case = FALSE,
                         fixed = TRUE,
                         costs = c(insertions = 5, deletions = 1, substitutions = 10),
                         counts = FALSE
  ))
}, codes$name_gen, generalise_antibiotic_name(codes$ab_name), USE.NAMES = FALSE))

codes$lev_pct <- codes$lev / nchar(codes$name)

View(codes)

import <- codes |> filter(lev <= 10 | name_gen == "PENICILLIN") |> as_tibble() |> mutate(ab = as.ab(ab_name, fast_mode = TRUE))

for (i in seq_len(NROW(import))) {
  # put them in the abbreviations
  abbr <- antimicrobials[which(antimicrobials$ab == import$ab[i]), "abbreviations"][[1]]
  new_abbr <- c(abbr[[1]], import$code[i])
  new_abbr <- new_abbr[!is.na(new_abbr)]
  antimicrobials[which(antimicrobials$ab == import$ab[i]), "abbreviations"][[1]] <- list(new_abbr)
}
