name: Bug Report
description: I think I found a bug!
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        You're probably improving the lives of many AMR package users :)
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description.
      placeholder: Description
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: AMR Package Version
      description: |
        What version of the AMR package are you running? You can retrieve this by running in R:

        ```r
        packageVersion("AMR")
        ```
      multiple: false
      options:
        - Latest CRAN version (2.1.1)
        - One of the latest GitHub versions (2.1.1.9xxx)
    validations:
      required: true
  - type: checkboxes
    id: field-impact
    attributes:
      label: Impacted Field
      description: Which field is probably impacted by this? You may select more than one, or choose none at all.
      options:
        - label: Medical (human) microbiology
        - label: Veterinary microbiology
        - label: Environmental microbiology

