name: Bug Report
description: I think I found a bug!
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        You're probably improving the lives of many AMR package users :)
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description.
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: reprex
    attributes:
      label: Minimal Reproducible Example (optional)
      description: Please include a short R code snippet that reproduces the problem, if possible.
      placeholder: 
        e.g.
        ```r
        ab_name("amoxicillin/clavulanic acid", language = "es")
        ```
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        > 💡 If you're not sure what's causing it, you can copy-paste your R session info using `sessionInfo()` or `devtools::session_info()` for us to help faster.
        
        Otherwise, please fill in the below AMR package version.
  - type: dropdown
    id: version
    attributes:
      label: AMR Package Version
      description: Which version of the AMR package are you running? You can retrieve this by running `packageVersion("AMR")` in R. If you are not running any of these versions, then please update first and check whether the bug still persists.
      multiple: false
      options:
        - ''
        - Latest CRAN version (3.0.0)
        - One of the latest GitHub versions (3.0.0.9xxx)
    validations:
      required: true
