name: Feature or Optimisation Request
description: I have an idea!
labels: "enhancement"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make a suggestion!

        We'll be happy to implement on a short notice if this improves the AMR package. Do note that **BY FAR** most of the content of the current version is because of collaborators like you! So, many thanks in advance.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description.
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case (optional)
      description: When or why would this be useful?
      placeholder: Describe a situation where this would help you or others.
    validations:
      required: false
