# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rsi_calc_S <- function(x, include_I) {
    .Call(`_AMR_rsi_calc_S`, x, include_I)
}

rsi_calc_R <- function(x, include_I) {
    .Call(`_AMR_rsi_calc_R`, x, include_I)
}

